#pragma checksum "..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BD7F638CADBD0189B7558D9034125BE4FB3E8B66"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Rekenmachine_;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Rekenmachine_ {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 57 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock OutputTextBlock;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Clearbtn;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Decimalbtn;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Sqrtbtn;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Squarebtn;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Sevenbtn;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Eigthbtn;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Ninebtn;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Fourbtn;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Fivebtn;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Sixbtn;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Threebtn;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Twobtn;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Onebtn;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Zerobtn;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button plusbtn;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Minusbtn;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Timesbtn;
        
        #line default
        #line hidden
        
        
        #line 229 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Dividebtn;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Eqaulsbtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.5.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Rekenmachine_;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.5.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.OutputTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.Clearbtn = ((System.Windows.Controls.Button)(target));
            
            #line 73 "..\..\..\MainWindow.xaml"
            this.Clearbtn.Click += new System.Windows.RoutedEventHandler(this.Clearbtn_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Decimalbtn = ((System.Windows.Controls.Button)(target));
            
            #line 83 "..\..\..\MainWindow.xaml"
            this.Decimalbtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Sqrtbtn = ((System.Windows.Controls.Button)(target));
            
            #line 92 "..\..\..\MainWindow.xaml"
            this.Sqrtbtn.Click += new System.Windows.RoutedEventHandler(this.Sqrtbtn_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.Squarebtn = ((System.Windows.Controls.Button)(target));
            
            #line 103 "..\..\..\MainWindow.xaml"
            this.Squarebtn.Click += new System.Windows.RoutedEventHandler(this.Sqaurebtn_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Sevenbtn = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\..\MainWindow.xaml"
            this.Sevenbtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.Eigthbtn = ((System.Windows.Controls.Button)(target));
            
            #line 121 "..\..\..\MainWindow.xaml"
            this.Eigthbtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.Ninebtn = ((System.Windows.Controls.Button)(target));
            
            #line 130 "..\..\..\MainWindow.xaml"
            this.Ninebtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Fourbtn = ((System.Windows.Controls.Button)(target));
            
            #line 139 "..\..\..\MainWindow.xaml"
            this.Fourbtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.Fivebtn = ((System.Windows.Controls.Button)(target));
            
            #line 148 "..\..\..\MainWindow.xaml"
            this.Fivebtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.Sixbtn = ((System.Windows.Controls.Button)(target));
            
            #line 157 "..\..\..\MainWindow.xaml"
            this.Sixbtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.Threebtn = ((System.Windows.Controls.Button)(target));
            
            #line 166 "..\..\..\MainWindow.xaml"
            this.Threebtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.Twobtn = ((System.Windows.Controls.Button)(target));
            
            #line 175 "..\..\..\MainWindow.xaml"
            this.Twobtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.Onebtn = ((System.Windows.Controls.Button)(target));
            
            #line 184 "..\..\..\MainWindow.xaml"
            this.Onebtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.Zerobtn = ((System.Windows.Controls.Button)(target));
            
            #line 193 "..\..\..\MainWindow.xaml"
            this.Zerobtn.Click += new System.Windows.RoutedEventHandler(this.Numbtn_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.plusbtn = ((System.Windows.Controls.Button)(target));
            
            #line 202 "..\..\..\MainWindow.xaml"
            this.plusbtn.Click += new System.Windows.RoutedEventHandler(this.Plusbtn_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.Minusbtn = ((System.Windows.Controls.Button)(target));
            
            #line 212 "..\..\..\MainWindow.xaml"
            this.Minusbtn.Click += new System.Windows.RoutedEventHandler(this.Minusbtn_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.Timesbtn = ((System.Windows.Controls.Button)(target));
            
            #line 223 "..\..\..\MainWindow.xaml"
            this.Timesbtn.Click += new System.Windows.RoutedEventHandler(this.Timesbtn_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.Dividebtn = ((System.Windows.Controls.Button)(target));
            
            #line 233 "..\..\..\MainWindow.xaml"
            this.Dividebtn.Click += new System.Windows.RoutedEventHandler(this.Dividebtn_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.Eqaulsbtn = ((System.Windows.Controls.Button)(target));
            
            #line 243 "..\..\..\MainWindow.xaml"
            this.Eqaulsbtn.Click += new System.Windows.RoutedEventHandler(this.Eqaulsbtn_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

